"""updata point

Revision ID: 17c777679b69
Revises: 398f0bc93d10
Create Date: 2016-07-07 08:51:07.464735

"""

# revision identifiers, used by Alembic.
revision = '17c777679b69'
down_revision = '398f0bc93d10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('points', sa.Column('body', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'body')
    op.drop_column('points', 'author_id')
    ### end Alembic commands ###
