"""update point time

Revision ID: 2a07017d9810
Revises: 4d33aec4b2cf
Create Date: 2016-07-10 10:23:33.467371

"""

# revision identifiers, used by Alembic.
revision = '2a07017d9810'
down_revision = '4d33aec4b2cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'timestamp')
    ### end Alembic commands ###
