"""update point Anonymous

Revision ID: 30d7dc2a5d84
Revises: 2a07017d9810
Create Date: 2016-07-10 11:48:23.204666

"""

# revision identifiers, used by Alembic.
revision = '30d7dc2a5d84'
down_revision = '2a07017d9810'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('Anonymous', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'Anonymous')
    ### end Alembic commands ###
