"""updata TagPost

Revision ID: 58e6dd02226d
Revises: 17c777679b69
Create Date: 2016-07-07 10:23:53.049265

"""

# revision identifiers, used by Alembic.
revision = '58e6dd02226d'
down_revision = '17c777679b69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
